runtime: python310  # Specifies the Python runtime version

instance_class: F2  # Optional: Choose the instance class for performance (F2 is a flexible instance with 2 CPUs)

env_variables:
  CLOUD_SQL_USERNAME: 1d
  CLOUD_SQL_PASSWORD: Um114020  # Note the correction here
  CLOUD_SQL_DATABASE_NAME: trunk_ladies_db
  CLOUD_SQL_CONNECTION_NAME: 'trunkladies-433304:asia-east1:trunkladiesinstance'
  MYSQL_CURSORCLASS: DictCursor
  SECRET_KEY: your_secret_key  # Replace with your actual secret key

handlers:
- url: /.*
  script: main.app  # This specifies the entry point for your Flask app
