runtime: python310  # Specifies the Python runtime version

env_variables:
  CLOUD_SQL_USERNAME: 1d
  CLOUD_SQL_PASSWORD: Um114020  # Note the correction here
  CLOUD_SQL_DATABASE_NAME: trunk_ladies_db
  CLOUD_SQL_CONNECTION_NAME: 'trunkladies-433304:asia-east1:trunkladiesinstance'
  MYSQL_CURSORCLASS: DictCursor
  SECRET_KEY: your_secret_key  # Replace with your actual secret key
