runtime: python39  # Specifies the Python runtime version

instance_class: F2  # Optional: Choose the instance class for performance (F2 is a flexible instance with 2 CPUs)

env_variables:
  CLOUD_SQL_USERNAME: '1d'
  CLOUD_SQL_Password: 'Um114020'
  CLOUD_SQL_DATABASE_NAME: 'trunk_ladies_db'
  CLOUD_SQL_CONNECTION_NAME: '104.199.210.86'
  MYSQL_CURSORCLASS: 'DictCursor'
  SECRET_KEY: 'your_secret_key'  # Replace with your actual secret key

